title: dijkstraj
email: jogchem@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://dijkstraj.github.io"
github_username: dijstraj

theme: minima
plugins:
  - jekyll-feed
